"""Add user.tg_link column

Revision ID: 0ff608cc9756
Revises: e4715258ca97
Create Date: 2024-05-12 17:54:08.152802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff608cc9756'
down_revision: Union[str, None] = 'e4715258ca97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_link_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tg_link_token')
    # ### end Alembic commands ###
