"""Add user.tg_id column

Revision ID: 6edcce752953
Revises: e4715258ca97
Create Date: 2024-05-12 12:24:48.843995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edcce752953'
down_revision: Union[str, None] = 'f9544ce8dde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###
