###
#@name Create transaction
POST http://{{host}}:{{port}}/transactions/
Content-Type: application/json
Authorization: {{Authorization}}

{
    "type": 1,
    "amount": 20
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}